import { Poppins, Open_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import { SiteLoader } from "../components/SiteLoader.jsx";
import { SpeedInsights } from "@vercel/speed-insights/next";
import Script from "next/script";
const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
});

const sans = Open_Sans({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-sans",
});

const BASE_URL = process.env.VERCEL_URL
  ? `https://${process.env.VERCEL_URL}`
  : "https://information-technology-services.vercel.app";

export const metadata = {
  title: { default: "Information Technology Services", template: "ITS | %s " },
  metadataBase: new URL(BASE_URL),
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${sans.variable} `}>
        <SpeedInsights />
        <SiteLoader>
          <Navbar />
          {children}

          <Script id="tawk-to" strategy="afterInteractive">
            {`
            var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
            (function(){
              var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
              s1.async=true;
              s1.src='https://embed.tawk.to/6992a3c16e20711c314164b7/1jhicvbf1';
              s1.charset='UTF-8';
              s1.setAttribute('crossorigin','*');
              s0.parentNode.insertBefore(s1,s0);
            })();
          `}
          </Script>

          <Footer />
        </SiteLoader>
      </body>
    </html>
  );
}
