

export const metadata = {
  title: { absolute: "Services | ITS", template: "Services | %s " },
  description: "Generated by create next app",
};

export default function ServicesLayout({ children }) {
  return (
    <html lang="en">
      <body>
          {children}
      </body>
    </html>
  );
}
